name: Notify central docs of update

on:
  push:
    paths:
      - 'docs/**'

jobs:
  notify-docs-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs site rebuild
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.DOCS_DEPLOY_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/vrui-vr/docs/actions/workflows/build-and-deploy.yml/dispatches \
            -d '{"ref":"main"}'
